version: "3.9"

services:
  frontend:
    build:
      context: ./idus-frontend
    container_name: idus-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./idus-backend
    container_name: idus-backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: idus-db
    environment:
      POSTGRES_USER: idususer
      POSTGRES_PASSWORD: iduspass
      POSTGRES_DB: idusdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: idus-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
