version: "3.9"

services:
  frontend:
    build:
      context: ./idus-frontend
    container_name: idus-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - idus-network

  backend:
    build:
      context: ./idus-backend
    container_name: idus-backend
    environment:
      DATABASE_NAME: idusdb
      DATABASE_USER: idususer
      DATABASE_PASSWORD: iduspass
      DATABASE_HOST: idus-db
      DATABASE_PORT: 5432
      ALLOWED_HOSTS: localhost,127.0.0.1,www.phelukas.com.br
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://127.0.0.1:8000,https://www.phelukas.com.br,http://www.phelukas.com.br
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - idus-network

  db:
    image: postgres:15-alpine
    container_name: idus-db
    environment:
      POSTGRES_USER: idususer
      POSTGRES_PASSWORD: iduspass
      POSTGRES_DB: idusdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - idus-network

  nginx:
    image: nginx:latest
    container_name: idus-nginx
    volumes:
      - /etc/letsencrypt/live/www.phelukas.com.br:/etc/letsencrypt/live/www.phelukas.com.br:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/keys:/etc/letsencrypt/keys:ro
      - ./nginx:/etc/nginx/conf.d # Monte a configuração do Nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - idus-network

volumes:
  postgres_data:

networks:
  idus-network:
