# Generated by Django 5.1.3 on 2024-12-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpoints', '0002_alter_workpoint_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpoint',
            name='weekday',
            field=models.CharField(default='desconhecido', editable=False, max_length=20),
            preserve_default=False,
        ),
    ]
