# Generated by Django 5.1.3 on 2024-12-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpoints', '0003_workpoint_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpoint',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='workpoint',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
