# Generated by Django 5.1.3 on 2025-06-06 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workpoints", "0004_workpoint_latitude_workpoint_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workpoint",
            index=models.Index(
                fields=["user", "timestamp"], name="workpoints__user_id_3e5a02_idx"
            ),
        ),
    ]
