# Generated by Django 5.1.3 on 2024-12-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='scale',
            field=models.CharField(choices=[('5x1', '5x1'), ('6x1', '6x1')], default='5x1', max_length=10),
        ),
    ]
