# Generated by Django 5.1.3 on 2024-12-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_scale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='scale',
            field=models.CharField(choices=[('5x1', '5x1'), ('6x1', '6x1'), ('12x36', '12x36'), ('4h', '4 horas diárias (Estagiários)'), ('6h', '6 horas diárias (Aprendizes)')], default='5x1', max_length=10),
        ),
    ]
