name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: idususer
          POSTGRES_PASSWORD: iduspass
          POSTGRES_DB: idusdb
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5
    env:
      DATABASE_NAME: idusdb
      DATABASE_USER: idususer
      DATABASE_PASSWORD: iduspass
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      SECRET_KEY: testsecret
      DEBUG: "True"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r idus-backend/requirements.txt

      - name: Run backend tests
        run: |
          cd idus-backend
          pytest

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: idus-frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: idus-frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: idus-frontend
        run: npm test --if-present

      - name: Lint backend
        run: |
          pip install black
          black --check idus-backend || true

      - name: Lint frontend
        working-directory: idus-frontend
        run: npm run lint || true
